"""added completion time for tasks

Revision ID: 169a9eb27ee1
Revises: ff84ef83c037
Create Date: 2026-04-15 18:52:17.819705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '169a9eb27ee1'
down_revision: Union[str, Sequence[str], None] = 'ff84ef83c037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tasks_completed_at'), 'tasks', ['completed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_completed_at'), table_name='tasks')
    op.drop_column('tasks', 'completed_at')
    # ### end Alembic commands ###
