"""index changes

Revision ID: 23537eb1f059
Revises: e1ab302cabe3
Create Date: 2026-04-26 22:14:05.675004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23537eb1f059'
down_revision: Union[str, Sequence[str], None] = 'e1ab302cabe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_is_active_start_time', 'meetings', ['is_active', 'start_time'], unique=False)
    op.create_index(op.f('ix_tasks_deadline'), 'tasks', ['deadline'], unique=False)
    op.drop_constraint(op.f('teams_name_key'), 'teams', type_='unique')
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.drop_index(op.f('ix_users_team_id'), table_name='users')
    op.create_index('ix_team_role', 'users', ['team_id', 'role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_team_role', table_name='users')
    op.create_index(op.f('ix_users_team_id'), 'users', ['team_id'], unique=False)
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.create_unique_constraint(op.f('teams_name_key'), 'teams', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_tasks_deadline'), table_name='tasks')
    op.drop_index('ix_is_active_start_time', table_name='meetings')
    # ### end Alembic commands ###
