"""add fastapi-users auth

Revision ID: 878c2fe07858
Revises: 5519fb418f58
Create Date: 2026-04-03 19:39:36.928437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '878c2fe07858'
down_revision: Union[str, Sequence[str], None] = '5519fb418f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tasks_executor_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_author_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['executor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_author_id_fkey'), 'tasks', 'users', ['author_id'], ['id'])
    op.create_foreign_key(op.f('tasks_executor_id_fkey'), 'tasks', 'users', ['executor_id'], ['id'])
    # ### end Alembic commands ###
