"""team codes

Revision ID: e1ab302cabe3
Revises: f3465df3b56c
Create Date: 2026-04-26 15:57:01.002488

"""
import secrets
import string
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1ab302cabe3'
down_revision: Union[str, Sequence[str], None] = 'f3465df3b56c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def generate_invite_code() -> str:
    alphabet = string.ascii_uppercase + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(12))


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('invite_code', sa.String(length=12), nullable=True))
    op.create_index(op.f('ix_teams_invite_code'), 'teams', ['invite_code'], unique=True)

    conn = op.get_bind()
    teams_table = sa.table('teams', sa.column('id'), sa.column('invite_code'))
    teams = conn.execute(sa.select(teams_table.c.id)).fetchall()
    for team in teams:
        new_code = generate_invite_code()
        conn.execute(teams_table.update().where(teams_table.c.id == team.id).values(invite_code=new_code))

    op.alter_column('teams', 'invite_code', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_invite_code'), table_name='teams')
    op.drop_column('teams', 'invite_code')
    # ### end Alembic commands ###
